name: Filter and Clean Subscriptions

on:
  schedule:
    - cron: '0 */6 * * *' # Автозапуск каждые 6 часов
  workflow_dispatch:      # Кнопка ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Subconverter via Docker
        run: |
          # Запускаем официальный Docker-контейнер subconverter
          # Он сам скачает, профильтрует 10000 серверов и сохранит готовый файл live_free.yaml
          docker run --rm -v ${{ github.workspace }}:/workspace tindy2013/subconverter:latest \
          ./subconverter -g --url "https://raw.githubusercontent.com/Au1rxx/free-vpn-subscriptions/main/output/clash.yaml" \
          --target clash --max_nodes 70 --udp false --sort true
          
          # Переносим созданный файл в нужное место
          mv sub.yaml live_free.yaml

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add live_free.yaml
          git commit -m "Update clean proxy list" || exit 0
          git push
